### ISSUE TITLE
Help with Shairport-Sync configuration for peppyalsa

### ISSUE THREAD

**Issue by dubaleeiro** [project-owner/peppyalsa.doc#1]
Hello, I am not sure wheter this is an issue, but would someone take a look at [this topic](https://github.com/mikebrady/shairport-sync/issues/1437) and try to give me a hand?

Thanks !

**Comment by project-owner** [comment]
Hi, I'm not sure what is the root cause of this issue. It looks very similar to another one:
https://github.com/mikebrady/shairport-sync/issues/1046
Regards

**Comment by dubaleeiro** [comment]
Hi !
Thanks a lot for the very good hint ! Issue solved here <https://github.com/mikebrady/shairport-sync/issues/1437#>
