### ISSUE TITLE
Plugin setup peppyalsa

### ISSUE THREAD

**Issue by AlexPtushkin** [project-owner/peppyalsa.doc#3]
My /home/pi/.asoundrc consists of:

pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw
  card 0
}
ctl.equal {
  type equal;
}

pcm.plugequal {
  type equal;
  slave.pcm bt
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}
pcm.bt {
    type plug
    slave.pcm {
        type bluealsa
        device "41:42:C4:33:46:32"
        profile "a2dp"
        delay -20000
    }
}

How to add configuration to it  VU Meter and Spectrum Analyzer?

**Comment by AlexPtushkin** [comment]
Will this be right?

pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw
  card 0
}
ctl.equal {
  type equal;
}

pcm.peppyalsa {
        type meter
        slave.pcm "hw:0,0"
        scopes.0 peppyalsa
}

pcm.plugequal {
  type equal;
  slave.pcm bt
  type softvol
  slave.pcm "peppyalsa"
  control {
          name "PCM"
          card 0
  }
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}
pcm.bt {
    type plug
    slave.pcm {
        type bluealsa
        device "41:42:C4:33:46:32"
        profile "a2dp"
        delay -20000
    }
}

pcm_scope.peppyalsa {
        type peppyalsa
        decay_ms 400
        meter "/home/pi/myfifo"
        meter_max 100
        meter_show 0
        spectrum "/home/pi/myfifosa"
        spectrum_max 100
        spectrum_size 30
}

pcm_scope_type.peppyalsa {
        lib /usr/local/lib/libpeppyalsa.so
}

pcm.dsp0 peppyalsa

**Comment by project-owner** [comment]
I don't have the answer right now. If you will find the solution please let me know.
https://www.diyaudio.com/community/threads/peppy-player.288412/post-7404831

**Comment by AlexPtushkin** [comment]
Hello!
Figured it out, everything worked!
Registered on the site.
Thank you!
Have a good day.

**Comment by project-owner** [comment]
Hi, what is the configuration which worked?

**Comment by AlexPtushkin** [comment]
Hi!
You have such a good project, but I’m slowly figuring it out.
Everything worked: meter and spectrum.

[asoundrc.txt](https://github.com/project-owner/peppyalsa.doc/files/12746428/asoundrc.txt)

Have a good day.
